React 룰 추가
ridi/eslint-config pull request #7
Opened 2018-02-01 05:16 UTC by antiline

2018-02-01 06:47 UTC, namenu requested changes

2018-02-01 06:47 UTC, namenu commented on index.js
> +const OFF = 0;
0, 1, 2 대신 "off", "warn", "error" 라고도 표기할 수 있습니다.
https://eslint.org/docs/user-guide/getting-started#configuration

2018-02-01 06:47 UTC, namenu commented on index.js
> +  'globals': {
`React`, `ReactDOM` 둘 다 명시적으로 import 하고 사용하는게 바람직해 보입니다.

2018-02-01 06:47 UTC, namenu commented on index.js
> +    'react/jsx-filename-extension': [ON, { 'extensions': ['.jsx'] }],
이 규칙을 포함하는 이유는 무엇인가요?

2018-02-02 02:28 UTC, kyungmi commented
`jsx-a11y/label-has-for` 관련 규칙도 수정해 보았습니다. 자세한 내용은 commit 메세지를 확인해주세요.

2018-02-02 02:34 UTC, antiline commented on index.js
> +    'react/jsx-filename-extension': [ON, { 'extensions': ['.jsx'] }],
UI 관련된 JSX 문법이 여러 파일에 난잡하게 위치하지않게 하기 위해 JSX 는 jsx 확장자 파일에만 넣도록 강제하는 룰 입니다.
React 특성상 완벽하게 MVC가 되지 않지만 그래도 V 코드를 한쪽에만 정리 할 수 있을 거라 생각해서 팀 내부에서는 사용하고 있습니다.
관련해서 전사적으로 공유할만한 룰이라 생각되서 추가했습니다.

2018-02-02 02:35 UTC, kyungmi commented on index.js
> +  },
global 변수에 `React`와 `ReactDOM`이 포함되어야 하는 이유는 무엇인가요?

2018-02-02 02:57 UTC, kyungmi commented on index.js
> +  plugins: ['react'],
`react` plugin을 명시적으로 써주신 이유가 있나요? `jsx-a11y` 도 함께 써주는게 좋을까요?

2018-02-02 02:59 UTC, kyungmi commented on index.js
> +    'react/jsx-filename-extension': ['warn', { extensions: ['.jsx'] }],
`react/jsx-filename-extension`은 이미 airbnb rule에 포함되어 있는 내용인데 `error`에서 `warn`으로 레벨을 낮추신 이유가 궁금하네요.

2018-02-05 02:37 UTC, antiline commented
airbnb 에 포함되어 있고, 느슨한거 빼고, 잘못 정리된것 빼니 `jsx-a11y/label-has-for`만 남는군요.
@namenu 해당 룰만 추가하고 정리하면 될것 같습니다.

2018-02-05 03:13 UTC, namenu approved these changes

2018-02-05 05:06 UTC, merged